version: '3.8'
services:
  web:
    build: ./flask_app
    ports:
      - "5001:5000"
    volumes:
      - ./flask_app:/app
    links:
      - mongodb
  mongodb:
    image: mongo:3.6
  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    environment: 
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    restart: always